version: '3.8'

services:
  azure-test-api:
    build: 
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: azure-test-api
    restart: unless-stopped
    ports:
      - "5050:5050"
    volumes:
      - ../logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=5050
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - azure-api-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: azure-test-api-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - azure-test-api
    networks:
      - azure-api-network

networks:
  azure-api-network:
    driver: bridge

volumes:
  nginx-logs:
